id = "vento-improved"
name = "Vento Improved"
version = "1.0.0"
schema_version = 1
authors = ["Deniz Akşimşek <deniz@aksimsek.tr>", "Bob Rockefeller"]
description = "Highlighting for the Vento templating language with YAML front matter support"
repository = "https://github.com/bobrocke/vento-improved"

[grammars.vento]
repository = "https://github.com/bobrocke/tree-sitter-better-vento/"
commit = "1e5b2f71d0a62490f5245410fdd67dddc4f5f698"
